version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:10.18.0-buster

commands:
  authenticate_npm:
    steps:
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
  npm_publish:
    steps:
      - run:
          name: Publish package
          command: npm publish
jobs:
  publish:
    executor: default
    steps:
      - checkout
      - authenticate_npm
      - npm_publish

workflows:
  build_and_publish_npm:
    jobs:
      - publish:
          filters:
            tags:
              only: /^qa-v.*/
            branches:
              ignore: /.*/