version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:10.18.0-buster

commands:
  npm_auth_setting:
    steps:
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
  npm_publish:
    steps:
      - run:
          name: Publish package
          command: npm publish
jobs:
  build:
    executor: default
    steps:
      - checkout
      - npm_auth_setting
      - npm_publish

workflows:
  build_and_test:
    jobs:
      - build:
        filters:
          tags:
            only: /^qa-v.*/
          branches:
            ignore: /.*/